-- ============================================================
--  ADD-ON: Certificates & Achievements
--  Run this ONCE in Supabase → SQL Editor → New query → Run.
--  Safe to run even if you already set up the other tables.
-- ============================================================

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  title text not null, issuer text, year text, "desc" text, link text, sort int default 0
);

alter table public.certificates enable row level security;

drop policy if exists "public read" on public.certificates;
drop policy if exists "admin write" on public.certificates;
create policy "public read" on public.certificates for select using (true);
create policy "admin write" on public.certificates for all
  using (public.is_admin()) with check (public.is_admin());

-- starter rows (optional — delete/edit later from the Admin panel)
insert into public.certificates (title, issuer, year, "desc", link, sort) values
  ('Machine Learning Specialization','Coursera','2024','Supervised & unsupervised learning, neural networks.','',1),
  ('Full-Stack Web Development','freeCodeCamp','2023','Responsive design, APIs, and databases.','',2),
  ('Hackathon Winner','College Tech Fest','2024','1st place — built an AI-powered study assistant.','',3);
