-- ============================================================
--  Dhruv Shrivastava — Portfolio database schema
--  Run this ENTIRE file once in Supabase → SQL Editor → New query → Run.
--  It creates the tables, opens them for public reading, and locks all
--  editing to a single admin account (your email).
-- ============================================================

-- 1) Who is allowed to edit? Only this email.
--    Change the email inside this function if you ever want a different admin.
create or replace function public.is_admin()
returns boolean
language sql stable
as $$
  select coalesce(auth.jwt() ->> 'email', '') = 'dhruvshrivastava1803@gmail.com';
$$;

-- ------------------------------------------------------------
-- 2) Tables
-- ------------------------------------------------------------
create table if not exists public.profile (
  id            int primary key default 1,
  brand         text, greeting text, first_name text, last_name text,
  role          text, tag text, bio text, availability text,
  resume_url    text, photo_url text, about text,
  github        text, linkedin text, twitter text, instagram text, email text,
  updated_at    timestamptz default now(),
  constraint single_row check (id = 1)
);

create table if not exists public.stats (
  id bigint generated by default as identity primary key,
  value text not null, label text not null, sort int default 0
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null, level int default 80, sort int default 0
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null, "desc" text, tags text, link text, sort int default 0
);

create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  role text not null, org text, period text, "desc" text, sort int default 0
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  title text not null, issuer text, year text, "desc" text, link text, image_url text, sort int default 0
);

-- Contact form submissions from visitors.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null, email text not null, body text not null,
  created_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 3) Turn on Row Level Security on every table
-- ------------------------------------------------------------
alter table public.profile    enable row level security;
alter table public.stats      enable row level security;
alter table public.skills     enable row level security;
alter table public.projects   enable row level security;
alter table public.experience enable row level security;
alter table public.certificates enable row level security;
alter table public.messages   enable row level security;

-- ------------------------------------------------------------
-- 4) Policies
--    Content tables: anyone can READ, only admin can WRITE.
-- ------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['profile','stats','skills','projects','experience','certificates']
  loop
    execute format('drop policy if exists "public read" on public.%I;', t);
    execute format('drop policy if exists "admin write" on public.%I;', t);
    execute format('create policy "public read" on public.%I for select using (true);', t);
    execute format('create policy "admin write" on public.%I for all using (public.is_admin()) with check (public.is_admin());', t);
  end loop;
end $$;

--    Messages: anyone can SUBMIT (insert), only admin can READ/delete.
drop policy if exists "anyone submit" on public.messages;
drop policy if exists "admin read"    on public.messages;
drop policy if exists "admin delete"  on public.messages;
create policy "anyone submit" on public.messages for insert with check (true);
create policy "admin read"    on public.messages for select using (public.is_admin());
create policy "admin delete"  on public.messages for delete using (public.is_admin());

-- ------------------------------------------------------------
-- 5) Seed starter content (safe to run once)
-- ------------------------------------------------------------
insert into public.profile (id, brand, greeting, first_name, last_name, role, tag, bio, availability, resume_url, photo_url, about, github, linkedin, twitter, instagram, email)
values (1, 'DS.', 'Hello, I''m', 'Dhruv', 'Shrivastava.', 'Computer Science Engineer', 'AI/ML Enthusiast',
  'I build immersive digital experiences and intelligent systems that solve real-world problems. Passionate about 3D, Interaction, and Innovation.',
  'Available for Freelance Projects', '#', '/dhruv.jpeg',
  'I''m a Computer Science Engineer who loves turning ambitious ideas into polished products.',
  'https://github.com/', 'https://linkedin.com/', 'https://twitter.com/', 'https://instagram.com/',
  'dhruvshrivastava.18032006@gmail.com')
on conflict (id) do nothing;

insert into public.stats (value, label, sort) values
  ('2+','Years Experience',1),('15+','Projects Completed',2),
  ('10+','Technologies',3),('5★','Client Reviews',4);

insert into public.skills (name, level, sort) values
  ('React & Next.js',92,1),('Python & ML',88,2),('Three.js / WebGL',80,3),
  ('Node & APIs',85,4),('UI / UX Design',83,5),('Cloud & DevOps',76,6);

insert into public.projects (title, "desc", tags, link, sort) values
  ('Neural Vision','Real-time object detection dashboard powered by a custom CNN.','Python, PyTorch, React','#',1),
  ('Orbit 3D','Interactive 3D product configurator built with Three.js.','Three.js, R3F, GLSL','#',2),
  ('FinFlow','Full-stack personal finance tracker with insights.','Next.js, Postgres, Charts','#',3);

insert into public.experience (role, org, period, "desc", sort) values
  ('Freelance Full-Stack Developer','Self-employed','2024 — Present','Building web apps and interactive experiences for clients worldwide.',1),
  ('ML Research Intern','Tech Lab','2023 — 2024','Worked on computer-vision models and data pipelines.',2);

insert into public.certificates (title, issuer, year, "desc", link, sort) values
  ('Machine Learning Specialization','Coursera','2024','Supervised & unsupervised learning, neural networks.','',1),
  ('Full-Stack Web Development','freeCodeCamp','2023','Responsive design, APIs, and databases.','',2),
  ('Hackathon Winner','College Tech Fest','2024','1st place — built an AI-powered study assistant.','',3);

-- ------------------------------------------------------------
-- 6) Storage bucket for uploaded certificate images
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('certificates', 'certificates', true)
on conflict (id) do nothing;

drop policy if exists "cert public read"  on storage.objects;
drop policy if exists "cert admin write"  on storage.objects;
drop policy if exists "cert admin update" on storage.objects;
drop policy if exists "cert admin delete" on storage.objects;
create policy "cert public read"  on storage.objects for select using (bucket_id = 'certificates');
create policy "cert admin write"  on storage.objects for insert with check (bucket_id = 'certificates' and public.is_admin());
create policy "cert admin update" on storage.objects for update using (bucket_id = 'certificates' and public.is_admin());
create policy "cert admin delete" on storage.objects for delete using (bucket_id = 'certificates' and public.is_admin());
